{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
    credentials: |-
        [default]
        aws_access_key_id = {{ .Values.secret.aws_access_key_id }}
        aws_secret_access_key = {{ .Values.secret.aws_secret_access_key }}
{{- end }}